//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HELPSTEIN.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxCompanyName {
            get {
                return ((string)(this["textBoxCompanyName"]));
            }
            set {
                this["textBoxCompanyName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Компания:")]
        public string LabelCompany {
            get {
                return ((string)(this["LabelCompany"]));
            }
            set {
                this["LabelCompany"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Имя:")]
        public string labelName {
            get {
                return ((string)(this["labelName"]));
            }
            set {
                this["labelName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Телефон:")]
        public string labelPhone {
            get {
                return ((string)(this["labelPhone"]));
            }
            set {
                this["labelPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Email:")]
        public string labelEmail {
            get {
                return ((string)(this["labelEmail"]));
            }
            set {
                this["labelEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Приоритет:")]
        public string groupBoxUrgency {
            get {
                return ((string)(this["groupBoxUrgency"]));
            }
            set {
                this["groupBoxUrgency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("неважно")]
        public string radioButton1 {
            get {
                return ((string)(this["radioButton1"]));
            }
            set {
                this["radioButton1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("важно")]
        public string radioButton2 {
            get {
                return ((string)(this["radioButton2"]));
            }
            set {
                this["radioButton2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("очень важно")]
        public string radioButton3 {
            get {
                return ((string)(this["radioButton3"]));
            }
            set {
                this["radioButton3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxName {
            get {
                return ((string)(this["textBoxName"]));
            }
            set {
                this["textBoxName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxPhone {
            get {
                return ((string)(this["textBoxPhone"]));
            }
            set {
                this["textBoxPhone"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBoxEmail {
            get {
                return ((string)(this["textBoxEmail"]));
            }
            set {
                this["textBoxEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Тип обращения:")]
        public string labelType {
            get {
                return ((string)(this["labelType"]));
            }
            set {
                this["labelType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string telegramTokenSettings {
            get {
                return ((string)(this["telegramTokenSettings"]));
            }
            set {
                this["telegramTokenSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string telegramChatIdSettings {
            get {
                return ((string)(this["telegramChatIdSettings"]));
            }
            set {
                this["telegramChatIdSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BotTelegramSettings {
            get {
                return ((bool)(this["BotTelegramSettings"]));
            }
            set {
                this["BotTelegramSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("23")]
        public string BitrixGROUP_ID {
            get {
                return ((string)(this["BitrixGROUP_ID"]));
            }
            set {
                this["BitrixGROUP_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BitrixACCOMPLICES {
            get {
                return ((string)(this["BitrixACCOMPLICES"]));
            }
            set {
                this["BitrixACCOMPLICES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string BitrixRESPONSIBLE_ID {
            get {
                return ((string)(this["BitrixRESPONSIBLE_ID"]));
            }
            set {
                this["BitrixRESPONSIBLE_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public string BitrixACCOMPLICES_1 {
            get {
                return ((string)(this["BitrixACCOMPLICES_1"]));
            }
            set {
                this["BitrixACCOMPLICES_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string BitrixACCOMPLICES_2 {
            get {
                return ((string)(this["BitrixACCOMPLICES_2"]));
            }
            set {
                this["BitrixACCOMPLICES_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("17")]
        public string BitrixACCOMPLICES_3 {
            get {
                return ((string)(this["BitrixACCOMPLICES_3"]));
            }
            set {
                this["BitrixACCOMPLICES_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BitrixToSends {
            get {
                return ((bool)(this["BitrixToSends"]));
            }
            set {
                this["BitrixToSends"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TelegramToSends {
            get {
                return ((bool)(this["TelegramToSends"]));
            }
            set {
                this["TelegramToSends"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBOXInvetoryPC {
            get {
                return ((string)(this["textBOXInvetoryPC"]));
            }
            set {
                this["textBOXInvetoryPC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBOXInvetoryMONITOR {
            get {
                return ((string)(this["textBOXInvetoryMONITOR"]));
            }
            set {
                this["textBOXInvetoryMONITOR"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string textBOXInvetoryOther {
            get {
                return ((string)(this["textBOXInvetoryOther"]));
            }
            set {
                this["textBOXInvetoryOther"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring />\r\n  <string>Прочее</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection TroubleTypes {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["TroubleTypes"]));
            }
            set {
                this["TroubleTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getRamSettings {
            get {
                return ((bool)(this["getRamSettings"]));
            }
            set {
                this["getRamSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getCpuSettings {
            get {
                return ((bool)(this["getCpuSettings"]));
            }
            set {
                this["getCpuSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getDiskSettings {
            get {
                return ((bool)(this["getDiskSettings"]));
            }
            set {
                this["getDiskSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getOpSettings {
            get {
                return ((bool)(this["getOpSettings"]));
            }
            set {
                this["getOpSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getVideoSettings {
            get {
                return ((bool)(this["getVideoSettings"]));
            }
            set {
                this["getVideoSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getMotheboardSettings {
            get {
                return ((bool)(this["getMotheboardSettings"]));
            }
            set {
                this["getMotheboardSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getMonitorSettings {
            get {
                return ((bool)(this["getMonitorSettings"]));
            }
            set {
                this["getMonitorSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getNetworksSettings {
            get {
                return ((bool)(this["getNetworksSettings"]));
            }
            set {
                this["getNetworksSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getSoftSettings {
            get {
                return ((bool)(this["getSoftSettings"]));
            }
            set {
                this["getSoftSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getProcessSettings {
            get {
                return ((bool)(this["getProcessSettings"]));
            }
            set {
                this["getProcessSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getServicesSettigs {
            get {
                return ((bool)(this["getServicesSettigs"]));
            }
            set {
                this["getServicesSettigs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getPrinterSettings {
            get {
                return ((bool)(this["getPrinterSettings"]));
            }
            set {
                this["getPrinterSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getUserInfoSettings {
            get {
                return ((bool)(this["getUserInfoSettings"]));
            }
            set {
                this["getUserInfoSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool getTeamViewerSettings {
            get {
                return ((bool)(this["getTeamViewerSettings"]));
            }
            set {
                this["getTeamViewerSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MailToSends {
            get {
                return ((bool)(this["MailToSends"]));
            }
            set {
                this["MailToSends"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExelinventoryToSends {
            get {
                return ((bool)(this["ExelinventoryToSends"]));
            }
            set {
                this["ExelinventoryToSends"] = value;
            }
        }
    }
}
